# my global config
global:
  scrape_interval: 5s
  evaluation_interval: 5s 

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["host.docker.internal:9090"]
  - job_name: "blackbox-exporter"
    static_configs:
      - targets: ["host.docker.internal:9115"]
  - job_name: "postgres-exorter"
    static_configs:
      - targets: ["host.docker.internal:9187"]
  
  - job_name: 'cms-blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - host.docker.internal:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: host.docker.internal:9115

  - job_name: 'postgres-blackbox'
    static_configs:
      - targets:
        - host.docker.internal:5432
    metrics_path: /probe
    params:
      module: [tcp_connect]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: host.docker.internal:9115
  
  - job_name: 'postgres-probe'
    metrics_path: /probe
    params:
      auth_module: [postgres]
    static_configs:
      - targets:
        - host.docker.internal:5432
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: host.docker.internal:9187