global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    site: 'prod'

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'thanos'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'thanos-sidecar:10902'
          - 'thanos-querier:10902'
          - 'thanos-store:10902'
          - 'thanos-compactor:10902'

  - job_name: 'minio'
    metrics_path: /minio/prometheus/metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['minio:9000']
